name: CI-CD Pipeline for Wisecow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: self-hosted 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: anishr0007
        password: Anish@8520

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: anishr0007/wisecow1:latest

  deploy:
    name: Deploy to Existing KIND Cluster
    runs-on: self-hosted   
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubectl for KIND
      run: |
        ls -ld ~/.kube
        mkdir -p /home/actions/.kube
        
        kind get kubeconfig --name wisecow-main > /home/actions/.kube/config
        
        kubectl cluster-info

    - name: Apply Namespace
      run: kubectl apply -f k8s/namespace.yml --validate=false

    - name: Apply Deployment
      run: kubectl apply -f k8s/deployment.yml --validate=false

    - name: Apply Service
      run: kubectl apply -f k8s/service.yml --validate=false

    - name: Verify rollout
      run: kubectl rollout status deployment/wisecow-deployment -n wisecow

    - name: portfrd
      run: kubectl port-forward service/wisecow -n wisecow 30080:4499 --address=0.0.0.0
      

      
