name: CI-CD Pipeline for Wisecow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: anishr0007
        password: dckr_pat_JKAcjW_ZM-e4QubGZDIaQAVTR9Q

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: anishr0007/wisecow1
#changed

  deploy:
    name: Deploy to KIND Cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Create Kind cluster
      uses: helm/kind-action@v1.7.0
      with:
        cluster_name: wisecow

    - name: Apply Namespace
      run: kubectl apply -f k8s/namespace.yml

    - name: Apply Deployment
      run: kubectl apply -f k8s/deployment.yml

    - name: Apply Service
      run: kubectl apply -f k8s/service.yml

    - name: Verify rollout
      run: kubectl rollout status deployment/wisecow-deployment -n wisecow
